//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dataset1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sotrudniki_View
    {
        public int Номер_сотрудника { get; set; }
        public Nullable<int> Номер_должности { get; set; }
        public Nullable<int> Номер_цвета { get; set; }
        public string Имя_сотрудника { get; set; }
        public string Фамилия_сотрудника { get; set; }
        public string Отчество_сотрудника { get; set; }
        public int Возраст { get; set; }
    }
}
