//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dataset1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sotrudniki
    {
        public int ID { get; set; }
        public Nullable<int> Dolzhnosti_ID { get; set; }
        public Nullable<int> Color_id { get; set; }
        public string FirstName { get; set; }
        public string SurName { get; set; }
        public string MiddleName { get; set; }
        public int Age { get; set; }
    
        public virtual Colors Colors { get; set; }
        public virtual Dolzhnocti Dolzhnocti { get; set; }
    }
}
