//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace p3265
{
    using System;
    using System.Collections.Generic;
    
    public partial class Courses
    {
        public int CourseID { get; set; }
        public string CourseName { get; set; }
        public string Instructor { get; set; }
        public int Credits { get; set; }
        public int IDStudent { get; set; }
    
        public virtual Students Students { get; set; }
    }
}
